spring:
  config:
    import: classpath:secret.yml


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV.DATABASE.URL}
    username: ${DEV.DATABASE.USERNAME}
    password: ${DEV.DATABASE.PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false


  jackson:
    time-zone: Asia/Seoul


logging:
  level:
    com.example.notification: DEBUG