spring:
  config:
    import: classpath:secret.yml


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV.DATABASE.URL}
    username: ${DEV.DATABASE.USERNAME}
    password: ${DEV.DATABASE.PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always